services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-nestjs-container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_nestjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
